const STORAGE='apLangRhetoricalPractice_v2_publishaudit';
const app=document.getElementById('app');
const passages={
  1:{title:'A Place That Asks Nothing',by:'Original AP-Style Speech by Elena Reyes',prompt:'After reading the speech “A Place That Asks Nothing,” write an essay that analyzes the rhetorical choices that Elena Reyes uses to convey her message.',html:`
<p>Last month, our planning board celebrated the latest phase of downtown redevelopment. Storefronts are filled, sidewalks are brighter, and visitors have more reasons to stay after sunset. Those changes matter. A vacant block does not become a community simply because we admire its history from a distance. Yet as we prepare for another round of improvements, we should notice what has quietly disappeared: the benches not attached to a café, the shaded corners without a vendor, the tables where no receipt is expected.</p>
<p>I am not asking us to resent a thriving restaurant or apologize for a busy shop. Commerce can animate a street, employ a neighbor, and give an old building new life. But a city is more than a marketplace. If every seat belongs to a customer, every table to a transaction, every patch of shade to a purchase, then we have not simply improved public space; we have rented every pause.</p>
<p>Think of the teenager waiting forty minutes for a ride after practice, the grandfather who walks downtown because his apartment feels too quiet, the parent who needs ten minutes while a child watches the fountain, the worker whose lunch break is too short to justify buying anything. None of them is failing to contribute to the city. Their presence is part of the city. A public place earns its name when people are permitted to exist there before they have proven their value as customers.</p>
<p>That freedom has consequences we rarely enter on a budget sheet. A truly public place allows us to pause, to observe, to encounter. The person we pass every morning becomes familiar. A child learns that older people belong in the same world she does. A disagreement can occur without anyone being required to leave when the bill arrives. These encounters are small, but civic life is made largely from small repetitions.</p>
<p>What kind of city tells a teenager, an elder, or a tired worker that rest requires a purchase? We need places where waiting is not loitering. We need places where conversation is not a transaction. We need places where a person can be present without first becoming a customer. If we remove such places one bench, one table, one shaded corner at a time, we should not be surprised when people begin to experience the city as consumers rather than neighbors.</p>
<p>So let cafés thrive and shops prosper. Let new businesses fill empty windows and bring life to neglected blocks. But let citizenship have rooms of its own. As we redesign our downtown, let us measure success not only by sales, leases, and foot traffic, but by whether a person with nothing to buy can still find a place to belong.</p>`},
  2:{title:'The Comfort of the Suggested',by:'Original AP-Style Essay',html:`
<p>A recommendation now arrives before desire has fully taken shape. The playlist continues when the song ends. The map proposes a route before we have considered another street. The article beneath the article waits with the confidence of a host who already knows what we will ask for next. Most of the time, this feels less like intrusion than relief. The world contains more music, information, restaurants, books, and possible routes than any person could reasonably examine. Selection is work, and the suggestion lightens it.</p>
<p>The appeal is therefore not trivial. Personalization can rescue us from abundance. It remembers what we forget, notices patterns we cannot easily see, and offers a starting point when the field of possibility is otherwise exhausting. Yet a guide repeated often enough can become an environment. When a system learns what we choose and uses those choices to arrange what we encounter next, it does not merely reflect preference. It can quietly tutor desire.</p>
<p>This tutoring rarely announces itself. The route is suggested, the song is queued, the article is placed before us. Each recommendation is small enough to feel inconsequential, and each can be refused. But refusal requires noticing that a choice has been arranged in the first place. A person who repeatedly accepts the most convenient option may still feel entirely self-directed while gradually seeing less of what falls outside the pattern already established.</p>
<p>Convenience is not coercion. We remain capable of closing the app, turning down an unfamiliar street, choosing the book no list has recommended. The important distinction is not between freedom and control as though only one can exist. It is between choosing from a field we have partly explored and choosing from a field another system has quietly narrowed for us. The second may still contain excellent choices; its limitation lies in how easily the boundary can disappear from view.</p>
<p>Surprise matters because preference is not finished when it is measured. We discover tastes by meeting things we did not know to request. A conversation introduces a writer. A wrong turn reveals a neighborhood. A song initially skipped becomes, months later, indispensable. The curated corridor can be comfortable precisely because it protects us from wasted time, irrelevant material, and disappointing experiments. It can also protect us from the accidents by which taste grows.</p>
<p>Because each recommendation reflects prior choices, because each accepted suggestion becomes information for what comes next, and because what comes next arrives with increasing confidence, the system does more than predict preference: it participates in shaping it. The process is circular without being sinister. We train the system; the system arranges the field; the arranged field influences the choices with which we train it again.</p>
<p>We should resist two easy conclusions: that personalization secretly determines us, and that recommendations are neutral simply because we remain free to ignore them. Both positions excuse us from attention. The more useful task is to become deliberate about where convenience serves us and where it narrows us—to accept guidance without mistaking it for the whole landscape, and to preserve some portion of our lives for the unrequested, the inefficient, and the surprising.</p>`}
};
const questions=[
{id:1,p:1,skill:'Rhetorical Situation & Purpose',stem:'The speaker’s primary intended audience is best understood as',choices:['local business owners concerned that public amenities may compete with private commerce','residents and planners deciding how redevelopment should balance commerce with public access','visitors who depend on downtown seating and shade while spending time between destinations','transportation officials deciding where benches and shelters should be placed throughout the city'],answer:'B',hint:'Look for the group positioned to make or influence decisions about redevelopment, public space, and civic belonging.'},
{id:2,p:1,skill:'Rhetorical Situation & Purpose',stem:'The broad cultural condition that most clearly prompts the speech is the growing tendency to',choices:['treat rising downtown populations as a reason to reduce the amount of space reserved for rest','view disagreement between residents and businesses as the main obstacle to successful redevelopment','assume that heavily used public spaces should be redesigned primarily to reduce crowding and congestion','judge public spaces mainly by the commerce they generate rather than the belonging they permit'],answer:'D',hint:'Choose the broad condition the speaker repeatedly challenges, not a narrower planning issue or conflict the passage does not establish.'},
{id:3,p:1,skill:'Tone',stem:'Which description most accurately characterizes the speaker’s tone in the opening two paragraphs?',choices:['measured and cautious, valuing commerce while questioning what is lost when it defines public space','nostalgic and frustrated, idealizing an earlier downtown while blaming businesses for weakening community ties','optimistic and confident, emphasizing the economic value of redevelopment before defending additional expansion','indignant and outraged, portraying planners as deliberately excluding residents who cannot afford to spend money'],answer:'A',hint:'Notice that the speaker grants real benefits to redevelopment and commerce before identifying a limit.'},
{id:4,p:1,skill:'Syntax',stem:'In the sentence “If every seat belongs to a customer, every table to a transaction, every patch of shade to a purchase,” the parallel structure primarily serves to',choices:['compare three public amenities in order to show that some forms of redevelopment are more intrusive than others','delay the speaker’s central claim until the audience has considered the financial cost of maintaining public space','accumulate examples showing how commercial expectations can extend into ordinary acts of resting and gathering','organize the sentence by location so the audience can picture the physical layout of a redesigned downtown'],answer:'C',hint:'Ask what the repeated grammatical pattern makes the audience notice about the reach of commercial expectations.'},
{id:5,p:1,skill:'Diction',stem:'The phrase “we have rented every pause” in paragraph 2 primarily serves to',choices:['frame public amenities as resources whose maintenance should be shared by businesses and residents','cast commercialization as extending beyond purchases into moments of rest and presence that should remain freely available','praise redevelopment for turning inactive public areas into spaces that generate economic activity throughout the day','make the planning dispute sound informal by comparing redevelopment decisions to an ordinary rental agreement'],answer:'B',hint:'Focus on what the verb “rented” implies when it is applied to a human “pause” and how that supports the speaker’s concern.'},
{id:6,p:1,skill:'Syntax',stem:'The repetition in “We need places where waiting is not loitering. We need places where conversation is not a transaction. We need places…” most directly functions as',choices:['epistrophe that emphasizes the repeated consequences of excluding nonpaying residents from downtown','polysyndeton that slows the passage so each type of public activity receives equal weight','antithesis that balances the economic purposes of downtown with the social purposes of public space','anaphora that intensifies the call for places where people can belong without purchasing anything'],answer:'D',hint:'Identify where the repeated words appear, then consider how the repetition strengthens the call to action.'},
{id:7,p:1,skill:'Rhetorical Question',stem:'In paragraph 5, the speaker asks, “What kind of city tells a teenager, an elder, or a tired worker that rest requires a purchase?” The rhetorical question primarily serves to',choices:['suggest that planners have deliberately targeted vulnerable residents when redesigning public areas','invite the audience to compare which groups have the strongest claim to limited downtown seating','personalize the consequences of commercialization and press the audience to judge the fairness of those consequences','shift the speech from a discussion of public space to a broader argument about economic inequality throughout the city'],answer:'C',hint:'Focus on why the speaker names recognizable people immediately before asking the audience to judge what the city is communicating to them.'},
{id:8,p:1,skill:'Tone',stem:'Across the speech, the tone shifts most clearly from',choices:['measured concern to increasingly urgent advocacy for protecting noncommercial forms of public belonging','nostalgic admiration of older public spaces to increasing frustration with residents who support redevelopment','cautious approval of business growth to a resigned acceptance that commercial interests will dominate civic planning','reflective restraint to indignant outrage at planners who have intentionally removed residents from the downtown area'],answer:'A',hint:'Compare the balanced acknowledgments early in the speech with the direct repeated appeals and final call to planners.'},
{id:9,p:1,skill:'Syntax',stem:'The tricolon in “to pause, to observe, to encounter” primarily emphasizes',choices:['the human experiences made possible when public space is not organized around purchasing','the chronological steps citizens should follow before entering a public disagreement','the physical activities that planners should prioritize when deciding where to place new amenities','the efficiency with which well-designed public spaces can satisfy several practical needs at once'],answer:'A',hint:'Consider what the three infinitives collectively suggest about the social value of unprogrammed public space.'},
{id:10,p:1,skill:'Rhetorical Situation & Purpose',stem:'The speaker’s overarching purpose is most accurately described as an effort to',choices:['convince planners to reduce commercial redevelopment until every neighborhood has equal access to downtown amenities','encourage residents to support public funding for benches, shade structures, and other downtown improvements','persuade the community to protect public spaces valued for access and belonging, not only commerce','criticize businesses for benefiting from redevelopment while contributing too little to the civic life around them'],answer:'C',hint:'Choose the purpose broad enough to include both the speaker’s support for thriving businesses and her defense of spaces that ask nothing in return.'},
{id:11,p:2,skill:'Rhetorical Situation & Purpose',stem:'The essay is most plausibly addressed to readers who',choices:['design recommendation systems and need guidance on improving the accuracy of personalization','avoid personalized technology because they believe any algorithmic influence threatens individual freedom','prefer human recommendations to digital suggestions because personal advice exposes them to a wider range of possibilities','routinely use personalized digital systems and may value their convenience without examining how they shape later choices'],answer:'D',hint:'Infer the audience from the familiar examples and the essay’s concern with ordinary users who accept recommendations as part of daily life.'},
{id:12,p:2,skill:'Tone',stem:'In the opening two paragraphs, the author’s attitude toward personalization is best described as',choices:['apprehensive, because the author suggests recommendation systems are likely to eliminate meaningful choice over time','measured, because the author values its usefulness while questioning how repeated guidance can shape preference','skeptical, because the author treats convenience as an excuse people use to avoid making thoughtful decisions','optimistic, because the author emphasizes how personalization solves the problem of overwhelming abundance'],answer:'B',hint:'Look for the author’s simultaneous acknowledgment of a real benefit and concern about what repeated guidance may become.'},
{id:13,p:2,skill:'Diction',stem:'The diction in the phrase “quietly tutor desire” primarily suggests that recommendation systems',choices:['replace individual preference with a set of choices created entirely by outside institutions','teach users to recognize better options by making their previous patterns easier to understand','can shape preference gradually and subtly rather than through an obvious act of control','exercise influence mainly when users consciously ask the system to narrow an overwhelming set of choices'],answer:'C',hint:'Focus on the implications of both “tutor” and “quietly”: influence can instruct without announcing itself as force.'},
{id:14,p:2,skill:'Syntax',stem:'In paragraph 3, the tricolon “The route is suggested, the song is queued, the article is placed before us” primarily serves to',choices:['compress several ordinary examples into a rhythmic series that emphasizes how widely recommendation operates in daily life','separate navigation, entertainment, and information in order to show that each requires a different kind of judgment','slow the paragraph so readers experience the deliberation the author believes recommendation systems discourage','arrange examples from least personal to most personal in order to show that recommendation becomes more intrusive over time'],answer:'A',hint:'Consider what the three parallel examples collectively demonstrate about the reach and normality of recommendation.'},
{id:15,p:2,skill:'Syntax',stem:'In paragraph 4, the emphatic sentence “Convenience is not coercion.” primarily serves to',choices:['condemn the assumption that users surrender all responsibility whenever they accept a recommendation','clarify the author’s position directly before distinguishing subtle influence from outright control','shift the essay from examining individual choices to evaluating the technical design of recommendation systems','minimize the concerns raised earlier by suggesting that personalization cannot meaningfully affect independent judgment'],answer:'B',hint:'Ask why the author states this brief complete claim before immediately qualifying the relationship between freedom and influence.'},
{id:16,p:2,skill:'Tone',stem:'The tone of the fifth and sixth paragraphs is best described as',choices:['sardonic and skeptical, mocking users who mistake algorithmic suggestions for expressions of personal taste','urgent and apprehensive, warning that repeated recommendations are rapidly eliminating opportunities for independent choice','reverent and nostalgic, presenting accidental discovery as a feature of an earlier culture that technology has destroyed','cautious and reflective, examining how convenience can narrow encounters without portraying the process as sinister'],answer:'D',hint:'The author traces a subtle risk in controlled language and explicitly says the process is circular “without being sinister.”'},
{id:17,p:2,skill:'Syntax',stem:'The antithesis in the final paragraph—“personalization secretly determines us” versus “recommendations are neutral simply because we remain free to ignore them”—primarily allows the author to',choices:['argue that both explanations accurately describe different kinds of recommendation systems','replace the essay’s concern with a new argument about the ethics of technology companies','suggest that users cannot know whether their preferences come from themselves or from digital systems','reject two oversimplified extremes before advancing a more qualified view of influence and choice'],answer:'D',hint:'Look at what the author does after naming the two opposing conclusions: neither is accepted as sufficient.'},
{id:18,p:2,skill:'Syntax',stem:'In paragraph 6, the periodic sentence beginning “Because each recommendation reflects prior choices” primarily serves to',choices:['present the author’s conclusion first so the following clauses can supply evidence for a claim already established','balance three independent causes in order to suggest that each affects preference to the same degree','delay the main assertion while accumulating conditions that emphasize the feedback loop between recommendation and preference','separate past choices from future recommendations so readers can distinguish prediction from influence'],answer:'C',hint:'Notice that several dependent clauses accumulate before the main assertion that the system participates in shaping preference.'},
{id:19,p:2,skill:'Diction',stem:'The phrase “curated corridor” is rhetorically effective primarily because it',choices:['compresses the idea of a path that feels orderly and useful while still limiting what a person is likely to encounter','suggests recommendation systems intentionally trap users by removing all opportunities to choose outside a fixed path','uses technical jargon to give the author authority when explaining how personalization systems organize information','portrays personalized recommendations as private spaces that shield users from disagreement with other people'],answer:'A',hint:'A corridor provides direction and access, but it also narrows movement; consider why “curated” complicates that image.'},
{id:20,p:2,skill:'Rhetorical Situation & Purpose',stem:'The author’s purpose is best understood as an attempt to',choices:['persuade readers to reject personalization whenever it replaces an entirely self-directed search for information or entertainment','encourage readers to use recommendation while deliberately preserving encounters beyond what prior preferences predict','convince technology companies to disclose more clearly how recommendation systems use previous choices to organize future options','demonstrate that algorithmic recommendations manipulate users even when users remain conscious of their freedom to refuse them'],answer:'B',hint:'The conclusion rejects both total alarm and total neutrality; choose the purpose that preserves that qualification and the call for deliberate attention.'}
];
function blankState(){return{screen:'entry',student:{first:'',last:'',period:''},answers:{},originalAnswers:{},intro:'',introGrade:null,readingStarted:{},readingEnds:{},questionEnds:{},currentQ:1,submitted:false,corrections:{},correctionAttempts:{},halfCreditRecovered:{},repairQ:null,firstScore:null};}
let state=load()||blankState();
function save(){localStorage.setItem(STORAGE,JSON.stringify(state));}
function load(){try{return JSON.parse(localStorage.getItem(STORAGE))}catch(e){return null}}
function esc(s=''){return s.replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
const INTRO_RUBRIC=[
{level:6,points:12,label:'Exceptional / College-Level',desc:'Complete TAG; precise audience and exigence; specific rhetorical choices; sophisticated, nuanced purpose; mature vocabulary and professional control.'},
{level:5,points:10,label:'Strong',desc:'Accurate TAG, audience, exigence, specific rhetorical choices, and clear purpose; polished and analytical, with slightly less nuance or precision than a 6.'},
{level:4,points:8,label:'Proficient',desc:'Includes the major required elements accurately; purpose and rhetorical situation are clear, though one element may be broad or underdeveloped.'},
{level:3,points:6,label:'Developing',desc:'Generally correct understanding, but one or more elements are vague, partial, or insufficiently connected; analysis lacks precision or depth.'},
{level:2,points:4,label:'Limited',desc:'Partial understanding; several required elements are missing, broad, or weakly connected; purpose may be reduced to a simple action.'},
{level:1,points:2,label:'Minimal',desc:'Very limited understanding; mostly summary, generic device language, incomplete rhetorical situation, or a vague purpose.'},
{level:0,points:0,label:'No Credit',desc:'Blank, off-topic, copied from the prompt without meaningful original analysis, or no genuine attempt.'}
];
const SKILL_GROUPS=[
{name:'Rhetorical Situation & Purpose',ids:[1,2,10,11,20]},
{name:'Tone & Tone Shift',ids:[3,8,12,16]},
{name:'Diction',ids:[5,13,19]},
{name:'Syntax',ids:[4,6,9,14,15,17,18]},
{name:'Rhetorical Devices & Effect',ids:[7]}
];
function introRubricHtml(){return `<details class="rubric-details"><summary>View the 1–6 Introduction Rubric</summary><div class="rubric-table">${INTRO_RUBRIC.filter(r=>r.level>0).map(r=>`<div class="rubric-row"><div><b>${r.level}</b><span>${r.points} pts</span></div><p><strong>${r.label}.</strong> ${r.desc}</p></div>`).join('')}</div></details>`;}
function gradeIntroduction(text){
  const raw=(text||'').trim();
  if(!raw)return{level:0,points:0,label:'No Credit',summary:'No introduction was submitted.'};
  const t=raw.toLowerCase().replace(/[“”]/g,'"').replace(/[’]/g,"'");
  const words=(raw.match(/[A-Za-z][A-Za-z’'\-]*/g)||[]);
  const wc=words.length;
  const sentences=(raw.match(/[.!?]+(?=\s|$)/g)||[]).length;
  const title=/place that asks nothing/.test(t);
  const author=/elena reyes|\breyes\b/.test(t);
  const genre=/\bspeech\b/.test(t);
  const tagCount=[title,author,genre].filter(Boolean).length;
  const audience=/\b(residents?|community members?|city residents?|civic[- ]minded|planners?|planning board|local residents?|citizens?|city leaders?|community)\b/.test(t);
  const publicSpace=/\b(public space|public spaces|public place|public places|downtown|redevelop\w*|commercial\w*|commerce|marketplace|purchase|purchasing|customer\w*|transaction\w*|profit|revenue|belong\w*|access|noncommercial|non-commercial)\b/.test(t);
  const preciseEx=publicSpace&&/\b(tendency|increasing\w*|growing|priority|priorit\w*|emphasis|focus\w*|treat\w*|judge\w*|measure\w*|redevelop\w*|commercializ\w*|proposal|planning|value\w*)\b/.test(t);
  const civicMeaning=/(public|civic|community|city).{0,55}(space|belong\w*|access|planning|redevelop\w*|citizenship)|(space|belong\w*|access|planning|redevelop\w*).{0,55}(public|civic|community|city)/.test(t);
  const devicePatterns={
    'rhetorical questions':/rhetorical question/,
    'anaphora':/\banaphora\b/,
    'parallelism':/\bparallel\w*\b/,
    'tricolon':/\btricolon\b/,
    'antithesis':/\bantithesis\b/,
    'diction':/\bdiction\b|loaded language/,
    'tone':/\btone\b/,
    'syntax':/\bsyntax\b/,
    'repetition':/\brepetition\b/
  };
  const devices=Object.entries(devicePatterns).filter(([_,rx])=>rx.test(t)).map(([name])=>name);
  const genericDevice=/rhetorical devices?/.test(t)&&devices.length===0;
  const effect=/\b(emphasiz\w*|challeng\w*|highlight\w*|reveal\w*|accumulat\w*|force\w*|prompt\w*|reinforc\w*|underscore\w*|illustrat\w*|demonstrat\w*|show\w*|convey\w*|stress\w*|personaliz\w*|press\w*|contrast\w*|expos\w*|clarif\w*|develop\w*)\b/.test(t);
  const purposeVerb=/\b(educat\w*|inspir\w*|encourag\w*|convinc\w*|prov\w*|demonstrat\w*|describ\w*|emphasiz\w*|inform\w*|motivat\w*|suggest\w*|persuad\w*|disprov\w*|reveal\w*|consol\w*|admir\w*|explain\w*|express\w*|discuss\w*|judg\w*|criticiz\w*|examin\w*|highlight\w*|contrast\w*|evaluat\w*|enlighten\w*|illustrat\w*|resist\w*|ridicul\w*|interpret\w*|question\w*|relat\w*|urg\w*|challeng\w*|advocat\w*|call\w*|prompt\w*|defend\w*|protect\w*|preserv\w*)\b/.test(t);
  const purposeIdea=/\b(public space|public spaces|belong\w*|access|citizenship|noncommercial|non-commercial|without (?:a )?purchase|without buying|not merely commercial|more than (?:a )?marketplace|community)\b/.test(t);
  const purposePresent=purposeVerb||purposeIdea;
  const purposeStrong=purposeVerb&&purposeIdea;
  const nuance=publicSpace&&purposeIdea&&/\b(rather than|not simply|not merely|while|even as|although|without|beyond|more than|both|not only|instead of|alongside|balance\w*|necessary|essential|responsible)\b/.test(t);
  const academicMatches=t.match(/\b(amid|ultimately|increasingly|civic|community|belonging|redevelopment|commercialization|commercial|noncommercial|preserve|protect|advocate\w*|recognize|emphasiz\w*|challeng\w*|persuad\w*|highlight\w*|reveal\w*|illustrat\w*|demonstrat\w*|examin\w*|contrast\w*|consequences?|assumptions?|access|citizenship|transaction|productivity)\b/g)||[];
  const sophisticationMatches=t.match(/\b(rather than|not simply|not merely|ultimately|depends?|essential|responsible|genuine|belonging|citizenship|without|beyond|more than|not only|alongside|balance\w*)\b/g)||[];
  const mechanicsOK=sentences>=2 && /^[A-Z“\"'‘]/.test(raw) && /[.!?]$/.test(raw);
  const relevant=title||author||publicSpace;
  if(!relevant || wc<15)return{level:0,points:0,label:'No Credit',summary:'The response does not provide enough relevant rhetorical-analysis writing to score.'};

  const basic=[tagCount>=2,audience,publicSpace,devices.length>=1,purposePresent];
  const basicCount=basic.filter(Boolean).length;
  let level=1;
  if(wc>=20 && basicCount>=2) level=2;
  if(wc>=24 && basicCount>=4 && !genericDevice) level=3;

  const majorComplete=(tagCount>=2)&&audience&&publicSpace&&(devices.length>=2)&&purposeStrong;
  if(wc>=34 && majorComplete && mechanicsOK && (effect||nuance)) level=4;

  const fullTag=tagCount===3;
  if(wc>=44 && fullTag&&audience&&preciseEx&&devices.length>=2&&purposeStrong&&mechanicsOK&&(effect||nuance)&&academicMatches.length>=3) level=5;
  if(wc>=52 && fullTag&&audience&&preciseEx&&devices.length>=2&&purposeStrong&&effect&&nuance&&civicMeaning&&mechanicsOK&&academicMatches.length>=5&&sophisticationMatches.length>=3) level=6;

  if(genericDevice) level=Math.min(level,2);
  if(!audience && !publicSpace) level=Math.min(level,2);
  if(devices.length===0) level=Math.min(level,2);
  if(!purposePresent) level=Math.min(level,2);
  if(wc<20)level=Math.min(level,1);

  const row=INTRO_RUBRIC.find(r=>r.level===level);
  const strengths=[];
  if(tagCount===3)strengths.push('complete T.A.G.'); else if(tagCount>=2)strengths.push('T.A.G. mostly present');
  if(audience&&publicSpace)strengths.push(preciseEx?'audience + exigence':'rhetorical situation');
  else if(audience||publicSpace)strengths.push('partial rhetorical situation');
  if(devices.length>=2)strengths.push(`${devices.slice(0,2).join(' + ')}`); else if(devices.length===1)strengths.push(devices[0]);
  if(effect)strengths.push('device function');
  if(purposeStrong)strengths.push(nuance?'nuanced purpose':'clear purpose'); else if(purposePresent)strengths.push('general purpose');
  if(mechanicsOK)strengths.push('professional sentence control');
  return{level,points:level*2,label:row.label,summary:strengths.length?`Detected: ${strengths.join(' • ')}.`:'Response shows a limited but relevant attempt.',wordCount:wc};
}
function skillStats(){return SKILL_GROUPS.map(g=>{const arr=g.ids.map(id=>questions[id-1]);const correct=arr.filter(q=>state.originalAnswers[q.id]===q.answer).length;return{name:g.name,correct,total:arr.length,pct:Math.round(correct/arr.length*100)};});}
function scoreSummary(){const mc=state.firstScore??questions.filter(q=>state.originalAnswers[q.id]===q.answer).length;const intro=state.introGrade||gradeIntroduction(state.intro);const recovered=Object.keys(state.halfCreditRecovered||{}).filter(id=>state.halfCreditRecovered[id]).length;const fullCredit=Number((mc*4.4).toFixed(1));const recoveryPoints=Number((recovered*2.2).toFixed(1));const mcPoints=Number((fullCredit+recoveryPoints).toFixed(1));const overall=Number((mcPoints+intro.points).toFixed(1));return{mc,intro,recovered,fullCredit,recoveryPoints,mcPoints,overall};}
function shell(inner,status=''){app.innerHTML=`<div class="shell"><div class="topbar"><div class="brand"><b>AP Language</b> // Rhetorical Analysis Practice Exam</div><div class="status">${status}</div></div><div class="card">${inner}</div></div>`}
function render(){if(state.screen==='entry')return entry();if(state.screen.startsWith('read'))return reading(+state.screen.slice(4));if(state.screen==='intro')return intro();if(state.screen==='question')return question();if(state.screen==='submit')return submit();if(state.screen==='corrections')return corrections();if(state.screen==='report')return report();}
function entry(){const resumable=state.student.first&&state.screen!=='entry';shell(`<div class="hero"><div class="entry"><div class="eyebrow">Timed Practice Exam // Two-Passage Examination</div><h1>Rhetorical<br>Analysis Practice</h1><p>Two passages. Twenty AP-style questions. One rhetorical-analysis introduction. Your progress is saved automatically on this browser.</p>${resumable?`<div class="resume"><b>Practice exam in progress:</b> ${esc(state.student.first)} ${esc(state.student.last)} — Period ${esc(state.student.period)}<div style="margin-top:10px"><button class="btn gold" onclick="resumeExam()">Resume Practice</button> <button class="btn secondary" onclick="resetExam()">Start New</button></div></div>`:`<div class="grid2"><div class="field"><label>First Name</label><input id="first" autocomplete="off"></div><div class="field"><label>Last Name</label><input id="last" autocomplete="off"></div></div><div class="field"><label>Class Period</label><select id="period"><option value="">Choose period</option>${[1,2,3,4,5,6,7].map(n=>`<option>${n}</option>`).join('')}</select></div><button class="btn" onclick="startExam()">Begin Practice Exam</button>`}</div></div>`,'Progress autosaves');}
function startExam(){const first=document.getElementById('first').value.trim(),last=document.getElementById('last').value.trim(),period=document.getElementById('period').value;if(!first||!last||!period)return alert('Enter first name, last name, and class period.');state=blankState();state.student={first,last,period};state.screen='read1';save();render();}
function resumeExam(){renderScreenFromState();}
function renderScreenFromState(){render();}
function resetExam(){if(confirm('Start a new practice exam? This will erase saved progress on this browser.')){localStorage.removeItem(STORAGE);state=blankState();render();}}
let tickHandle=null;
function setTimer(end,elId,mode,passageNum=null){clearInterval(tickHandle);function tick(){const el=document.getElementById(elId);if(!el)return clearInterval(tickHandle);const ms=end-Date.now();if(ms<=0){el.textContent=mode==='q'?'TIME EXPIRED — ANSWER STILL ACCEPTED':'00:00';el.classList.add('expired');if(mode==='read'){clearInterval(tickHandle);const btn=document.getElementById('readNext');if(btn){btn.textContent='Reading Time Complete — Begin Questions';btn.disabled=true;}setTimeout(()=>{if(state.screen===`read${passageNum}`)finishReading(passageNum)},350);}return;}const sec=Math.ceil(ms/1000),m=Math.floor(sec/60),s=sec%60;el.textContent=`${m}:${String(s).padStart(2,'0')}`;}tick();tickHandle=setInterval(tick,500)}
function reading(p){if(!state.readingStarted[p]){state.readingStarted[p]=Date.now();state.readingEnds[p]=Date.now()+7*60*1000;save()}const ps=passages[p];shell(`<div class="exam-head"><div><div class="phase">Passage ${p} // Reading</div><b>${esc(ps.title)}</b></div><div id="timer" class="timer"></div></div><div class="reading-wrap"><div class="passage-pane"><h2>${esc(ps.title)}</h2><div class="byline">${esc(ps.by)}</div>${ps.html}</div><div class="side-pane"><div><div class="eyebrow">Reading Window</div><h3>Read and annotate mentally.</h3><p class="instructions">You have <b>7 minutes</b> to read. You may move on early when you are finished. The passage will remain visible during every question.</p><p class="mini">Closing the browser will not erase your progress. The timer will not restart when you return.</p></div><button id="readNext" class="btn gold" onclick="finishReading(${p})">Finished Reading — Begin Questions</button></div></div>`,`${esc(state.student.first)} ${esc(state.student.last)} • Period ${esc(state.student.period)}`);setTimer(state.readingEnds[p],'timer','read',p);}
function finishReading(p){state.currentQ=p===1?1:11;state.screen='question';save();render();}
function question(){const q=questions[state.currentQ-1],p=q.p,ps=passages[p];if(!state.questionEnds[q.id]){state.questionEnds[q.id]=Date.now()+2*60*1000;save()}const chosen=state.answers[q.id]||'';shell(`<div class="exam-head"><div><div class="phase">Passage ${p} // Question ${p===1?q.id:q.id-10} of 10</div><b>${esc(q.skill)}</b></div><div id="timer" class="timer"></div></div><div class="qwrap"><div class="passage-pane"><h2>${esc(ps.title)}</h2><div class="byline">${esc(ps.by)}</div>${ps.html}</div><div class="qpanel"><div class="qmeta">Question ${q.id} • ${esc(q.skill)}</div><div class="stem">${esc(q.stem)}</div>${q.choices.map((c,i)=>{const L='ABCD'[i];return`<button class="choice ${chosen===L?'selected':''}" onclick="choose('${L}')"><span class="letter">${L}</span><span>${esc(c)}</span></button>`}).join('')}<div class="navrow"><button class="btn secondary" onclick="backQuestion()" ${q.id===1||q.id===11?'disabled':''}>Previous</button><button class="btn" onclick="nextQuestion()" ${!chosen?'disabled':''}>${q.id===10?'Write Introduction':q.id===20?'Review & Submit':'Next Question'}</button></div><p class="mini">If the timer reaches zero, you may still answer with no penalty.</p></div></div>`,`${esc(state.student.first)} ${esc(state.student.last)} • Period ${esc(state.student.period)}`);setTimer(state.questionEnds[q.id],'timer','q');}
function choose(L){state.answers[state.currentQ]=L;save();render();}
function backQuestion(){state.currentQ--;save();render();}
function nextQuestion(){if(!state.answers[state.currentQ])return; if(state.currentQ===10){state.screen='intro'}else if(state.currentQ===20){state.screen='submit'}else state.currentQ++;save();render();}
function intro(){const p=passages[1];shell(`<div class="exam-head"><div><div class="phase">Passage 1 // Writing</div><b>Rhetorical Analysis Introduction</b></div><div class="timer">12 POINTS</div></div><div class="intro"><div class="passage-pane"><h2>${esc(p.title)}</h2><div class="byline">${esc(p.by)}</div>${p.html}</div><div class="intro-panel"><div class="passage-sticky-note">Passage 1 remains visible on the left while you write.</div><div class="formula"><div class="eyebrow">Prompt</div><h3>${esc(p.prompt)}</h3><p class="instructions">Write the introductory paragraph only. The introduction is worth <b>12 points</b> of the 100-point practice exam and is scored on a <b>1–6 rubric</b>: 1=2 pts, 2=4 pts, 3=6 pts, 4=8 pts, 5=10 pts, 6=12 pts.</p><div class="formula-box"><b>T.A.G. + RHETORICAL SITUATION</b><br><span class="mini">Title • Author/Speaker • Genre • Intended Audience • Exigence</span></div><div class="formula-box"><b>DEVICES + AUTHOR’S PURPOSE</b><br><span class="mini">Preview specific rhetorical choices you will analyze and state precisely what the speaker hopes to accomplish.</span></div>${introRubricHtml()}<p class="mini rubric-note">The game scores the paragraph against this rubric after final submission. Your exact introduction will also appear on the Final Accuracy Report.</p></div><div class="writing-label"><div class="qmeta">Your Introduction</div><span class="mini">Autosaves as you type</span></div><textarea id="introText" class="intro-box" oninput="saveIntro()" placeholder="Write your introduction here...">${esc(state.intro)}</textarea><div class="navrow"><button class="btn secondary" onclick="state.screen='question';state.currentQ=10;save();render()">Back to Question 10</button><button class="btn" onclick="goPassage2()" ${state.intro.trim().length<40?'disabled':''}>Continue to Passage 2</button></div></div></div>`,`${esc(state.student.first)} ${esc(state.student.last)} • Period ${esc(state.student.period)}`);}
function saveIntro(){state.intro=document.getElementById('introText').value;save();const b=document.querySelector('.navrow .btn:not(.secondary)');if(b)b.disabled=state.intro.trim().length<40;}
function goPassage2(){if(state.intro.trim().length<40)return alert('Complete your introductory paragraph before continuing.');state.screen='read2';save();render();}
function submit(){const missing=questions.filter(q=>!state.answers[q.id]);shell(`<div class="submit-zone"><div class="submit-card"><div class="eyebrow">Practice Exam Checkpoint</div><h2>Ready to Submit?</h2><p class="instructions">Once submitted, your <b>20 multiple-choice answers and introduction are locked for scoring</b>. Each multiple-choice item is worth <b>4.4 points</b> (88 total), and the introduction is worth <b>12 points</b>, for a 100-point practice exam. Any missed multiple-choice questions will move into required corrections. A missed multiple-choice question earns <b>half credit (2.2 points)</b> only if it is corrected correctly on the <b>first correction attempt</b>. Later corrections are still required, but do not earn points.</p><div class="formula-box">Multiple Choice: <b>${20-missing.length}/20 answered</b><br>Introduction: <b>${state.intro.trim()?'Saved':'Missing'}</b></div>${missing.length?`<p class="warn">You still have unanswered questions.</p><button class="btn secondary" onclick="goFirstMissing()">Return to Missing Question</button>`:`<button class="btn danger" onclick="finalSubmit()">Submit Practice Exam</button>`}</div></div>`,`${esc(state.student.first)} ${esc(state.student.last)} • Period ${esc(state.student.period)}`);}
function goFirstMissing(){state.currentQ=questions.find(q=>!state.answers[q.id]).id;state.screen='question';save();render();}
function finalSubmit(){state.originalAnswers={...state.answers};state.submitted=true;state.firstScore=questions.filter(q=>state.originalAnswers[q.id]===q.answer).length;state.introGrade=gradeIntroduction(state.intro);state.corrections={};state.correctionAttempts={};state.halfCreditRecovered={};state.screen='corrections';save();render();}
function missed(){return questions.filter(q=>state.originalAnswers[q.id]!==q.answer)}
function corrections(){const m=missed(),done=m.filter(q=>state.corrections[q.id]===q.answer).length;const allDone=m.length===done;if(allDone){state.screen='report';save();return report()}shell(`<div class="correction-head"><div class="eyebrow">Required Corrections // Signal Recovery</div><h2 class="screen-title" style="font-size:2.8rem">Repair the Analysis Signal</h2><p class="instructions">Your first-attempt multiple-choice accuracy and introduction score have already been recorded. Every red signal marks a missed item. <b>Correct it on your first correction attempt to recover half credit (2.2 points).</b> If the first correction is wrong, keep working until the signal is restored; later attempts are required but earn no additional points. <b>All corrections are required before the Final Accuracy Report unlocks.</b></p><p><span class="badge">Signals Restored ${done}/${m.length}</span><span class="badge">First-Attempt MC ${state.firstScore}/20</span><span class="badge">Half-Credit Recoveries ${Object.keys(state.halfCreditRecovered||{}).filter(id=>state.halfCreditRecovered[id]).length}</span></p></div><div class="signal-grid">${m.map(q=>{const ok=state.corrections[q.id]===q.answer;return`<button class="signal ${ok?'correct':'damaged'}" onclick="openRepair(${q.id})"><div class="wave">∿∿∿∿∿∿∿∿∿∿∿</div><b>Question ${q.id}</b><span class="mini">${ok?'SIGNAL RESTORED':'DAMAGED — REPAIR REQUIRED'}</span></button>`}).join('')}</div><div class="repair" id="repairZone">${state.repairQ?repairHtml(state.repairQ):'<div class="repair-box"><b>Select a red signal to begin corrections.</b></div>'}</div>`,`${esc(state.student.first)} ${esc(state.student.last)} • Corrections Required`);}
function openRepair(id){state.repairQ=id;save();corrections();document.getElementById('repairZone')?.scrollIntoView({behavior:'smooth'});}
function repairHtml(id){const q=questions[id-1],p=passages[q.p],current=state.corrections[id]||'',correct=current===q.answer,attempts=(state.correctionAttempts||{})[id]||0,half=!!(state.halfCreditRecovered||{})[id];return`<div class="repair-split"><div class="passage-pane correction-passage"><h2>${esc(p.title)}</h2><div class="byline">${esc(p.by)}</div>${p.html}</div><div class="repair-box"><div class="qmeta">Correction • Question ${id} • ${esc(q.skill)}</div><div class="stem">${esc(q.stem)}</div>${q.choices.map((c,i)=>{const L='ABCD'[i];return`<button class="choice ${current===L?'selected':''}" onclick="repairChoose(${id},'${L}')" ${correct?'disabled':''}><span class="letter">${L}</span><span>${esc(c)}</span></button>`}).join('')}${current?`<div class="feedback ${correct?'good':'bad'}">${correct?(half?'Signal restored — first correction attempt correct. <b>Half credit earned: +2.2 points.</b>':'Signal restored. Correction accepted; no half credit because the first correction attempt was incorrect.'):`Not yet. This was correction attempt ${attempts}. Analytical cue: ${esc(q.hint)}`}</div>`:''}</div></div>`}
function repairChoose(id,L){if(state.corrections[id]===questions[id-1].answer)return;state.correctionAttempts=state.correctionAttempts||{};state.halfCreditRecovered=state.halfCreditRecovered||{};state.correctionAttempts[id]=(state.correctionAttempts[id]||0)+1;state.corrections[id]=L;if(L===questions[id-1].answer && state.correctionAttempts[id]===1)state.halfCreditRecovered[id]=true;save();corrections();}
function report(){
  if(!state.introGrade)state.introGrade=gradeIntroduction(state.intro);
  const sc=scoreSummary();
  const stats=skillStats();
  const p1=questions.slice(0,10).filter(q=>state.originalAnswers[q.id]===q.answer).length;
  const p2=questions.slice(10).filter(q=>state.originalAnswers[q.id]===q.answer).length;
  shell(`<div class="report"><div class="eyebrow">Final Accuracy Report // Corrections Complete</div><h2 class="report-name">${esc(state.student.first)} ${esc(state.student.last)} — Period ${esc(state.student.period)}</h2>
  <div class="score-summary">
    <div class="metric primary"><div class="metric-label">Overall Score</div><div class="metric-value">${sc.overall}<span>/100</span></div><div class="metric-note">MC ${sc.mcPoints}/88 + Intro ${sc.intro.points}/12</div></div>
    <div class="metric"><div class="metric-label">Multiple Choice</div><div class="metric-value">${sc.mc}<span>/20</span></div><div class="metric-note">First-attempt correct • ${sc.mcPoints}/88 points after ${sc.recovered} half-credit recoveries</div></div>
    <div class="metric"><div class="metric-label">Introduction</div><div class="metric-value">${sc.intro.level}<span>/6</span></div><div class="metric-note">${sc.intro.points}/12 points • ${esc(sc.intro.label)}</div></div>
  </div>
  <div class="report-grid"><div class="scorecard"><div class="qmeta">Multiple-Choice Data // First Attempt</div><p><span class="badge">Corrections Complete</span><span class="badge">Passage 1 ${p1}/10</span><span class="badge">Passage 2 ${p2}/10</span><span class="badge">Half-Credit Recoveries ${sc.recovered}</span></p><h3>Skill Breakdown</h3>${stats.map(x=>`<div class="skill"><span>${esc(x.name)}</span><b>${x.correct}/${x.total} <small>${x.pct}%</small></b></div>`).join('')}<div class="intro-grade-box"><div class="qmeta">Introduction Rubric</div><div class="intro-level">${sc.intro.level}/6 <span>${sc.intro.points}/12 pts</span></div><p>${esc(sc.intro.summary||'')}</p></div><p class="mini" style="margin-top:18px">Overall score = 4.4 points for each first-attempt correct multiple-choice answer + 2.2 points for each missed item corrected correctly on the first correction attempt + introduction rubric points. Skill data and the /20 count remain based on first-attempt accuracy.</p></div><div class="writing-card"><div class="qmeta" style="color:#675c49">Rhetorical Analysis Introduction</div><h3>Student Response</h3><div class="student-writing">${esc(state.intro)}</div></div></div><div class="footer-actions"><button class="btn" onclick="window.print()">Print / Save Report</button><button class="btn secondary" onclick="copyReport()">Copy Student Summary</button></div></div>`,`${esc(state.student.first)} ${esc(state.student.last)} • Final Report`);
  save();
}
function copyReport(){const sc=scoreSummary();const stats=skillStats();const skills=stats.map(x=>`${x.name}: ${x.correct}/${x.total} (${x.pct}%)`).join('\n');const txt=`${state.student.first} ${state.student.last} | Period ${state.student.period}\nOVERALL: ${sc.overall}/100\nMultiple Choice first-attempt correct: ${sc.mc}/20\nMultiple Choice points: ${sc.mcPoints}/88 (${sc.recovered} half-credit recoveries = +${sc.recoveryPoints} pts)\nIntroduction: ${sc.intro.level}/6 = ${sc.intro.points}/12 points\nCorrections: Complete\n\nSKILL BREAKDOWN — FIRST ATTEMPT\n${skills}\n\nINTRODUCTION:\n${state.intro}`;navigator.clipboard?.writeText(txt).then(()=>alert('Summary copied.')).catch(()=>alert('Copy unavailable in this browser.'));}
render();
